version: "3"

volumes:
  postgres_data:
      driver: local

services:
 postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    networks:
      - rails-api

networks:
  rails-api: